//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Cli.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ImportCommandStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ImportCommandStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Aspire.Cli.Resources.ImportCommandStrings", typeof(ImportCommandStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        internal static string AzureSubcommandDescription {
            get {
                return ResourceManager.GetString("AzureSubcommandDescription", resourceCulture);
            }
        }
        
        internal static string BicepSubcommandDescription {
            get {
                return ResourceManager.GetString("BicepSubcommandDescription", resourceCulture);
            }
        }
        
        internal static string TerraformSubcommandDescription {
            get {
                return ResourceManager.GetString("TerraformSubcommandDescription", resourceCulture);
            }
        }
        
        internal static string SubscriptionOption {
            get {
                return ResourceManager.GetString("SubscriptionOption", resourceCulture);
            }
        }
        
        internal static string ResourceGroupOption {
            get {
                return ResourceManager.GetString("ResourceGroupOption", resourceCulture);
            }
        }
        
        internal static string OutputOption {
            get {
                return ResourceManager.GetString("OutputOption", resourceCulture);
            }
        }
        
        internal static string NameOption {
            get {
                return ResourceManager.GetString("NameOption", resourceCulture);
            }
        }
        
        internal static string PathOption {
            get {
                return ResourceManager.GetString("PathOption", resourceCulture);
            }
        }
        
        internal static string ModeOption {
            get {
                return ResourceManager.GetString("ModeOption", resourceCulture);
            }
        }
        
        internal static string AuthenticatingWithAzure {
            get {
                return ResourceManager.GetString("AuthenticatingWithAzure", resourceCulture);
            }
        }
        
        internal static string SelectSubscription {
            get {
                return ResourceManager.GetString("SelectSubscription", resourceCulture);
            }
        }
        
        internal static string SelectResourceGroup {
            get {
                return ResourceManager.GetString("SelectResourceGroup", resourceCulture);
            }
        }
        
        internal static string DiscoveringResources {
            get {
                return ResourceManager.GetString("DiscoveringResources", resourceCulture);
            }
        }
        
        internal static string SelectResources {
            get {
                return ResourceManager.GetString("SelectResources", resourceCulture);
            }
        }
        
        internal static string NoResourcesFound {
            get {
                return ResourceManager.GetString("NoResourcesFound", resourceCulture);
            }
        }
        
        internal static string GeneratingAppHost {
            get {
                return ResourceManager.GetString("GeneratingAppHost", resourceCulture);
            }
        }
        
        internal static string ImportComplete {
            get {
                return ResourceManager.GetString("ImportComplete", resourceCulture);
            }
        }
        
        internal static string ConfirmImport {
            get {
                return ResourceManager.GetString("ConfirmImport", resourceCulture);
            }
        }
        
        internal static string UnsupportedResourceSkipped {
            get {
                return ResourceManager.GetString("UnsupportedResourceSkipped", resourceCulture);
            }
        }
        
        internal static string ComputeResourceDetected {
            get {
                return ResourceManager.GetString("ComputeResourceDetected", resourceCulture);
            }
        }
        
        internal static string AuthenticationFailed {
            get {
                return ResourceManager.GetString("AuthenticationFailed", resourceCulture);
            }
        }
        
        internal static string ResourceDiscoveryFailed {
            get {
                return ResourceManager.GetString("ResourceDiscoveryFailed", resourceCulture);
            }
        }
        
        internal static string CompilingBicep {
            get {
                return ResourceManager.GetString("CompilingBicep", resourceCulture);
            }
        }
        
        internal static string ParsingTerraformFiles {
            get {
                return ResourceManager.GetString("ParsingTerraformFiles", resourceCulture);
            }
        }
        
        internal static string BicepCliNotFound {
            get {
                return ResourceManager.GetString("BicepCliNotFound", resourceCulture);
            }
        }
        
        internal static string NoBicepFilesFound {
            get {
                return ResourceManager.GetString("NoBicepFilesFound", resourceCulture);
            }
        }
        
        internal static string NoTerraformFilesFound {
            get {
                return ResourceManager.GetString("NoTerraformFilesFound", resourceCulture);
            }
        }
        
        internal static string NoIaCResourcesFound {
            get {
                return ResourceManager.GetString("NoIaCResourcesFound", resourceCulture);
            }
        }
        
        internal static string BicepCompileFailed {
            get {
                return ResourceManager.GetString("BicepCompileFailed", resourceCulture);
            }
        }
        
        internal static string BicepImportFailed {
            get {
                return ResourceManager.GetString("BicepImportFailed", resourceCulture);
            }
        }
        
        internal static string TerraformImportFailed {
            get {
                return ResourceManager.GetString("TerraformImportFailed", resourceCulture);
            }
        }
        
        internal static string TerraformFileAccessFailed {
            get {
                return ResourceManager.GetString("TerraformFileAccessFailed", resourceCulture);
            }
        }
        
        internal static string IaCImportComplete {
            get {
                return ResourceManager.GetString("IaCImportComplete", resourceCulture);
            }
        }
        
        internal static string AzureFileAccessFailed {
            get {
                return ResourceManager.GetString("AzureFileAccessFailed", resourceCulture);
            }
        }
        
        internal static string AzureImportFailed {
            get {
                return ResourceManager.GetString("AzureImportFailed", resourceCulture);
            }
        }
    }
}
