// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System.Globalization;
using System.Text;

namespace Aspire.Cli.Import;

/// <summary>
/// Generates AppHost project files from imported infrastructure resources.
/// </summary>
internal sealed class AppHostCodeGenerator : IAppHostCodeGenerator
{
    private const int SectionHeaderWidth = 60;

    private static readonly HashSet<string> s_csharpKeywords =
    [
        "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked",
        "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else",
        "enum", "event", "explicit", "extern", "false", "finally", "fixed", "float", "for",
        "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock",
        "long", "namespace", "new", "null", "object", "operator", "out", "override", "params",
        "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed", "short",
        "sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw", "true",
        "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using", "virtual",
        "void", "volatile", "while"
    ];

    public string GenerateProgramCs(IReadOnlyList<ImportedResource> resources, string sourceLabel, ImportMode mode = ImportMode.Existing, string? resourceGroup = null)
    {
        var sb = new StringBuilder();
        var modeLabel = mode == ImportMode.Existing ? "existing" : "new";

        sb.AppendLine(CultureInfo.InvariantCulture, $"// Auto-generated by 'aspire import' from '{sourceLabel}' (mode: {modeLabel})");
        sb.AppendLine();
        sb.AppendLine("var builder = DistributedApplication.CreateBuilder(args);");

        var supported = resources.Where(r => r.SupportLevel == ImportSupportLevel.Supported).ToList();
        var placeholders = resources.Where(r => r.SupportLevel == ImportSupportLevel.Placeholder).ToList();
        var unsupported = resources.Where(r => r.SupportLevel == ImportSupportLevel.Unsupported).ToList();

        if (supported.Count > 0)
        {
            var variableNames = AssignUniqueVariableNames(supported);
            var groups = supported
                .Select((r, i) => (Resource: r, VarName: variableNames[i]))
                .GroupBy(x => x.Resource.FriendlyName ?? x.Resource.Category.ToString());

            foreach (var group in groups)
            {
                sb.AppendLine();
                sb.AppendLine(FormatSectionHeader(group.Key));

                foreach (var (resource, varName) in group)
                {
                    if (mode == ImportMode.Existing)
                    {
                        var rgArg = resourceGroup is not null
                            ? $"\"{resourceGroup}\""
                            : "null";
                        sb.AppendLine(CultureInfo.InvariantCulture, $"var {varName} = builder.{resource.AspireBuilderMethod}(\"{resource.SourceResourceName}\").RunAsExisting(\"{resource.SourceResourceName}\", {rgArg});");
                    }
                    else
                    {
                        sb.AppendLine(CultureInfo.InvariantCulture, $"var {varName} = builder.{resource.AspireBuilderMethod}(\"{resource.SourceResourceName}\");");
                    }
                }
            }
        }

        if (placeholders.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine(FormatSectionHeader("Compute / Workloads (TODO)"));

            foreach (var resource in placeholders)
            {
                var pascalName = ToPascalCase(resource.SourceResourceName);
                var friendlyLabel = resource.FriendlyName ?? resource.SourceType;
                sb.AppendLine(CultureInfo.InvariantCulture, $"// {friendlyLabel}: {resource.SourceResourceName}");
                sb.AppendLine(CultureInfo.InvariantCulture, $"// TODO: Replace with builder.AddProject<Projects.{pascalName}>(\"{resource.SourceResourceName}\")");
            }
        }

        if (unsupported.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine(FormatSectionHeader("Unsupported resources (informational)"));

            foreach (var resource in unsupported)
            {
                sb.AppendLine(CultureInfo.InvariantCulture, $"// - {resource.SourceResourceName} ({resource.SourceType})");
            }
        }

        sb.AppendLine();
        sb.AppendLine("builder.Build().Run();");

        return sb.ToString();
    }

    public string GenerateCsproj(IReadOnlyList<ImportedResource> resources, string projectName)
    {
        var packages = resources
            .Where(r => r.SupportLevel == ImportSupportLevel.Supported && !string.IsNullOrEmpty(r.NuGetPackage))
            .Select(r => r.NuGetPackage!)
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .Order(StringComparer.OrdinalIgnoreCase)
            .ToList();

        var sb = new StringBuilder();
        sb.AppendLine("<Project Sdk=\"Microsoft.NET.Sdk\">");
        sb.AppendLine();
        sb.AppendLine("  <PropertyGroup>");
        sb.AppendLine("    <OutputType>Exe</OutputType>");
        sb.AppendLine("    <TargetFramework>net10.0</TargetFramework>");
        sb.AppendLine("    <ImplicitUsings>enable</ImplicitUsings>");
        sb.AppendLine("    <Nullable>enable</Nullable>");
        sb.AppendLine("    <IsAspireHost>true</IsAspireHost>");
        sb.AppendLine("  </PropertyGroup>");
        sb.AppendLine();
        sb.AppendLine("  <ItemGroup>");
        sb.AppendLine("    <!-- TODO: Set package versions to match your Aspire installation -->");
        sb.AppendLine("    <PackageReference Include=\"Aspire.AppHost.Sdk\" Version=\"10.0.0-preview.5\" />");

        foreach (var package in packages)
        {
            sb.AppendLine(CultureInfo.InvariantCulture, $"    <PackageReference Include=\"{package}\" />");
        }

        sb.AppendLine("  </ItemGroup>");
        sb.AppendLine();
        sb.AppendLine("</Project>");

        return sb.ToString();
    }

    internal static string SanitizeResourceName(string name)
    {
        if (string.IsNullOrWhiteSpace(name))
        {
            return "resource";
        }

        var sb = new StringBuilder();
        var capitalizeNext = false;

        foreach (var ch in name)
        {
            if (ch is '-' or '_' or '.')
            {
                capitalizeNext = true;
                continue;
            }

            if (!char.IsLetterOrDigit(ch))
            {
                continue;
            }

            if (sb.Length == 0)
            {
                // First character must be a letter (or underscore, but we use letter convention).
                if (char.IsDigit(ch))
                {
                    sb.Append('r');
                    sb.Append(ch);
                }
                else
                {
                    sb.Append(char.ToLowerInvariant(ch));
                }

                capitalizeNext = false;
                continue;
            }

            if (capitalizeNext)
            {
                sb.Append(char.ToUpperInvariant(ch));
                capitalizeNext = false;
            }
            else
            {
                sb.Append(ch);
            }
        }

        if (sb.Length == 0)
        {
            return "resource";
        }

        var result = sb.ToString();
        return s_csharpKeywords.Contains(result) ? "@" + result : result;
    }

    internal static string FormatSectionHeader(string title)
    {
        // Format: // ── {title} ──────────
        var prefix = $"// ── {title} ";
        var remainingWidth = SectionHeaderWidth - prefix.Length;
        var dashes = remainingWidth > 0 ? new string('─', remainingWidth) : string.Empty;
        return prefix + dashes;
    }

    internal static IReadOnlyList<string> AssignUniqueVariableNames(IReadOnlyList<ImportedResource> resources)
    {
        var names = new string[resources.Count];
        var nameCount = new Dictionary<string, int>(StringComparer.Ordinal);

        for (var i = 0; i < resources.Count; i++)
        {
            var baseName = SanitizeResourceName(resources[i].SourceResourceName);
            names[i] = baseName;

            if (nameCount.TryGetValue(baseName, out var count))
            {
                nameCount[baseName] = count + 1;
            }
            else
            {
                nameCount[baseName] = 1;
            }
        }

        // Second pass: add numeric suffixes for duplicates.
        var suffixTracker = new Dictionary<string, int>(StringComparer.Ordinal);

        for (var i = 0; i < names.Length; i++)
        {
            var baseName = names[i];

            if (nameCount[baseName] > 1)
            {
                if (!suffixTracker.TryGetValue(baseName, out var suffix))
                {
                    suffix = 1;
                }

                names[i] = baseName + suffix.ToString(CultureInfo.InvariantCulture);
                suffixTracker[baseName] = suffix + 1;
            }
        }

        return names;
    }

    private static string ToPascalCase(string name)
    {
        if (string.IsNullOrWhiteSpace(name))
        {
            return "Resource";
        }

        var sb = new StringBuilder();
        var capitalizeNext = true;

        foreach (var ch in name)
        {
            if (ch is '-' or '_' or '.')
            {
                capitalizeNext = true;
                continue;
            }

            if (!char.IsLetterOrDigit(ch))
            {
                continue;
            }

            if (sb.Length == 0 && char.IsDigit(ch))
            {
                sb.Append('R');
                sb.Append(ch);
                capitalizeNext = false;
                continue;
            }

            if (capitalizeNext)
            {
                sb.Append(char.ToUpperInvariant(ch));
                capitalizeNext = false;
            }
            else
            {
                sb.Append(ch);
            }
        }

        return sb.Length == 0 ? "Resource" : sb.ToString();
    }
}
